#!/bin/bash
#
# functions	virt-extpack function library
#

## Tests if the OS is supported by this script (only Red Hat is supported)
is_a_supported_os() {
	IS_SUPPORTED=0
	# through /proc/version
	if [ -r /proc/version ]; then
		grep "Red Hat" /proc/version > /dev/null 2>&1
		[ $? -eq 0 ] && IS_SUPPORTED=1
	fi
	echo $IS_SUPPORTED
}

## Tests if the Vmware Tools is already installed in this box
check_vmware() {
	echo "TODO: check vmwaretools"
}

## Installs Vmware Tools
install_vmware() {
	echo "TODO: install vmwaretools"
}

## Tests if the Xen Tools is already installed in this box
check_xen() {
	echo "TODO: check xentools"
}

## Installs Xen Tools
install_xen() {
	echo "TODO: install xentools"
}

## Tests if the Virtualbox Guest Additions is already installed in this box
check_virtualbox() {
	lsmod | grep vbox > /dev/null 2>&1
}

## Installs Virtualbox Guest Additions
install_virtualbox() {
	# Installing the virtualbox guest additions
	LOG=$1
	yum install -y wget gcc cpp glibc-headers glibc-devel make kernel-headers kernel-devel perl >> $LOG 2>&1
	if [ $? -ne 0 ]; then
		echo "Coudn't install tools to compile and install Virtualbox Guest Additions. See $LOG for more details."
		return 1
	fi

	VBOX_VERSION=$(curl http://download.virtualbox.org/virtualbox/LATEST.TXT)
	cd /tmp
	rm -f VBoxGuestAdditions_$VBOX_VERSION.iso
	wget -a $LOG http://download.virtualbox.org/virtualbox/$VBOX_VERSION/VBoxGuestAdditions_$VBOX_VERSION.iso
	if [ $? -ne 0 ]; then
		echo "Coudn't fetch the Virtualbox Guest Additions ISO. See $LOG for more details."
		return 1
	fi

	mkdir /tmp/mnt-vboxguest-iso
	mount -o loop VBoxGuestAdditions_$VBOX_VERSION.iso /tmp/mnt-vboxguest-iso >> $LOG 2>&1
	if [ $? -ne 0 ]; then
		echo "Coudn't mount the Virtualbox Guest Additions ISO. See $LOG for more details."
		return 1
	fi

	sh /tmp/mnt-vboxguest-iso/VBoxLinuxAdditions.run >> $LOG 2>&1
	if [ $? -ne 0 ]; then
		echo "VBoxLinuxAdditions.run failed. See $LOG for more details."
		return 1
	fi

	umount /tmp/mnt-vboxguest-iso >> $LOG 2>&1
	if [ $? -ne 0 ]; then
		echo "Coudn't umount /tmp/mnt-vboxguest-iso. See $LOG for more details."
		return 1
	fi

	rm -rf /tmp/mnt-vboxguest-iso >> $LOG 2>&1
	rm -f VBoxGuestAdditions_$VBOX_VERSION.iso >> $LOG 2>&1

	yum remove -y wget gcc cpp glibc-headers glibc-devel make kernel-headers kernel-devel perl >> $LOG 2>&1
	if [ $? -ne 0 ]; then
		echo "Coudn't uninstall build tools Virtualbox Guest Additions. See $LOG for more details."
		return 1
	fi
	return 0
}
