#!/bin/bash
#
# virt-extpack	Ensures the extention pack is present in your virtual machine
#
# chkconfig: 345 98 99
# description: Ensures the extention pack is present in your virtual machine

# Source init function library
. /etc/rc.d/init.d/functions

# Source virt-extpack function library
. /var/lib/virt-extpack/functions

RETVAL=0
prog="virt-extpack"
lockfile=/var/lock/subsys/$prog
logfile=/var/log/$prog.log

[ -f $lockfile ] && exit 0

if [ $(is_a_supported_os) -ne 1 ]; then
	echo "this script doesn't support your operating system."
	exit 1
fi

command -v virt-what > /dev/null 2>&1
if [ $? -ne 0 ]; then
	echo "please install virt-what (http://people.redhat.com/~rjones/virt-what/) to proceed."
	exit 1
fi

touch $lockfile
echo > $logfile

echo -n "Starting virt-extpack execution: " | tee -a $logfile
HYPERVISOR=$(virt-what)
case "$HYPERVISOR" in
	vmware)
		check_vmware
		install_vmware
		;;
	xen|xen-dom0|xen-domU|xen-hvm)
		check_xen
		install_xen
		;;
	virtualbox)
		check_virtualbox
		if [ $? -eq 0 ]; then
			echo -n "Virtualbox Guest Additions is already installed and loaded." | tee -a $logfile
			success
		else
			echo -n "Installing the Virtualbox Guest Additions "
			install_virtualbox $logfile && success || failure
		fi
		;;
	*)
		echo "hypervisor $HYPERVISOR not supported!"
		RETVAL=1
		;;
esac

rm -f $lockfile

exit $RETVAL
